---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-agent-conf
  labels:
    app: opencensus
    component: oc-agent-conf
data:
  oc-agent-config: |
    receivers:
      opencensus: 
        address: "localhost:55678"
    exporters:
      stackdriver:
        project: "{{PROJECT-ID}}"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: oc-agent
  labels:
    app: opencensus
    component: oc-agent
spec:
  template:
    metadata:
      labels:
        app: opencensus
        component: oc-agent
    spec:
      containers:
      - command:
          - "/ocagent_linux"
          - "--config=/conf/oc-agent-config.yaml"
        image: omnition/opencensus-agent:0.1.6
        name: oc-agent
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 55678
        - containerPort: 55679
        volumeMounts:
        - name: oc-agent-config-vol
          mountPath: /conf
      volumes:
        - configMap:
            name: oc-agent-conf
            items:
              - key: oc-agent-config
                path: oc-agent-config.yaml
          name: oc-agent-config-vol
